direction: down

# Pages
AppShell: {
  label: "App Shell MFE"
  style: { fill: "#d9f2d9"  }

  NavBar: "Navigation" {
    style: { fill: "#cce5ff"}    
  }
}

DashboardMFE: {
  style: { fill: "#d9f2d9"  }

  Page: {
    label: "Dashboard Page"
    style: { fill: "#ffe5cc" }
    RecommendationComponent: "Top 5 Products Component"
    PurchaseHistoryComponent: "Top 5 Purchase History Component"
  }
}


ProductCatalogMFE: {
  label: "Product Catalog MFE"
  style: { fill: "#d9f2d9"  }
  
  Page: {
    label: "Product Catalog Page"
    style: { fill: "#ffe5cc" }
  }

   Components: {
    top5: {
      label: "Top 5 Products Component"
      style: { fill: "#cce5ff"}    
    }
  }
}


PurchaseHistoryMFE: {
  label: "Product History MFE"
  style: { fill: "#d9f2d9" }

  Page: {
    label: "Purchase History Page"
    style: { fill: "#ffe5cc" }
  }

  Components: {
    top5: {
      label: "Top 5 Purchase History Component"
      style: { fill: "#cce5ff"}    
    }
  }
}

AppShell.Navbar -> DashboardMFE.Page: "localhost:5001"
AppShell.Navbar -> ProductCatalogMFE.Page: "localhost:5002/product-catalogs"
AppShell.Navbar -> PurchaseHistoryMFE.Page: "localhost:5003/purchase-histories"


DashboardMFE.Page.RecommendationComponent -> ProductCatalogMFE.Components.Top5: "localhost:5002/components/top-5"
DashboardMFE.Page.PurchaseHistoryComponent -> PurchaseHistoryMFE.Components.Top5: "localhost:5003/components/top-5"



