direction: down

browser: {
  label: "Browser"
}

server: {
  label: "Server"
  group: {
    label: ""
    varnish: {
      label: "Varnish Server\nlocalhost:8080"
      shape: cloud
    }

    decision: { 
      shape: diamond
      label: "Is Resource \n Cached?"
    }

    varnish -> decision

    decision -> varnish: "Return cached Heading" {
      style: dashed
      label: "True"
    }
  }

  nodejs: {
    label: "Node.js Server\nlocalhost:8081"
    shape: cloud
  }

  group.decision -> nodejs: "Forward request" {
    label: "False"
  }
}

browser -> server.group.varnish: "Get Heading"
server.group.varnish -> browser: "Response Heading"
